// Home-page bottom-row icons: lucide line icons -> 24x24 JPEG on black -> PROGMEM headers.
// Run: node _gen_home_icons.cjs   (from this dir)
// Out: ../../img/temperature.h / humidity.h (same arrays, swapped in place).
// Color: #929292 = RGB(146,146,146) = COL_INK_3 - the exact grey the temp/humidity values use,
// so icon + value read as one quiet unit and the visual center stays on the clock.
// JPEG: baseline / 4:4:4 chroma / q90 - TJpgDec compatible (same encode chain as the health icons).
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const GREY = '#929292';
const SIZE = 24;  // icon bottom edge 237 = y 213 + 24; keep in sync with the drawJpg calls

const PICKS = [
  ['temperature', 'https://api.iconify.design/lucide/thermometer.svg'],
  ['humidity',    'https://api.iconify.design/lucide/droplet.svg'],
];

(async () => {
  for (const [name, url] of PICKS) {
    const res = await fetch(url + '?color=' + encodeURIComponent(GREY));
    if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
    let svg = await res.text();
    svg = svg.replace(/width="[^"]*" height="[^"]*"/, `width="${SIZE}" height="${SIZE}"`);
    const jpg = await sharp(Buffer.from(svg))
      .resize(SIZE, SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .flatten({ background: { r: 0, g: 0, b: 0 } })          // flatten alpha onto black = srcRGB x alpha
      .jpeg({ quality: 90, chromaSubsampling: '4:4:4', progressive: false })
      .toBuffer();
    let header = `// Auto-generated by tools/logos/_gen_home_icons.cjs - home bottom-row line icon (${SIZE}x${SIZE} JPEG, black bg).\n`;
    header += `// Source: lucide ${name} (ISC), recolored to #929292 = COL_INK_3 to pair with the values.\n`;
    header += `#include <pgmspace.h>\nconst uint8_t ${name}[] PROGMEM = {\n`;
    for (let i = 0; i < jpg.length; i += 16) {
      const row = [...jpg.slice(i, i + 16)].map(b => '0x' + b.toString(16).padStart(2, '0'));
      header += '\t' + row.join(', ') + ',\n';
    }
    header += '};\n';
    fs.writeFileSync(path.join(__dirname, '..', '..', 'img', `${name}.h`), header);
    console.log(`OK  ${name}  ${jpg.length} bytes`);
  }
})();
