// Health-page icon assets: 4 colored SVGs -> 88x88 JPEG on black -> PROGMEM C header.
// Run: node _gen_health_icons.cjs   (from this dir; reads ../icons/color/)
// Out: ../../img/health_icons.h  (+ preview copies in ../icons/firmware/)
// JPEG: baseline / 4:4:4 chroma (no color bleed on thin strokes) / q90 - TJpgDec compatible.
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const COLOR_DIR = path.join(__dirname, '..', 'icons', 'color');
const OUT_DIR = path.join(__dirname, '..', 'icons', 'firmware');
const IMG_DIR = path.join(__dirname, '..', '..', 'img');
fs.mkdirSync(OUT_DIR, { recursive: true });

// Index order must match healthActivity in the firmware: 0 water, 1 toilet, 2 eyes, 3 neck, 4 kegel
// All six are fluent-emoji-flat (MIT) full-color art (eyes = custom flat eye) for a uniform, vivid set.
const PICKS = [
  ['icon_water_jpg',  '00--water--fluent-emoji-flat-droplet.svg'],
  ['icon_toilet_jpg', '05--toilet--fluent-emoji-flat-toilet.svg'],
  ['icon_eyes_jpg',   '08--eyes--custom-flat-eye.svg'],
  ['icon_neck_jpg',   '14--neck--fluent-emoji-flat-person-in-lotus-position.svg'],
  ['icon_kegel_jpg',  '16--kegel--fluent-emoji-flat-peach.svg'],
  ['icon_stand_jpg',  '18--stand--fluent-emoji-flat-person-standing.svg'],
];

const ICON_SIZE = 100;  // rendered 1:1 by TJpgDec; keep in sync with the health-page drawJpg call

(async () => {
  let header = `// Auto-generated by tools/logos/_gen_health_icons.cjs - health-page colored icons (${ICON_SIZE}x${ICON_SIZE} JPEG, black bg).
// Sources: fluent-emoji-flat droplet / toilet / person-in-lotus-position / peach (all MIT); custom flat eye.
#include <pgmspace.h>
`;

  for (const [name, file] of PICKS) {
    const jpg = await sharp(path.join(COLOR_DIR, file))
      .resize(ICON_SIZE, ICON_SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .flatten({ background: { r: 0, g: 0, b: 0 } })          // flatten alpha onto black = srcRGB x alpha
      .jpeg({ quality: 90, chromaSubsampling: '4:4:4', progressive: false })
      .toBuffer();
    fs.writeFileSync(path.join(OUT_DIR, name.replace('_jpg', `_${ICON_SIZE}.jpg`)), jpg);
    header += `const uint8_t ${name}[] PROGMEM = {\n`;
    for (let i = 0; i < jpg.length; i += 16) {
      const row = [...jpg.slice(i, i + 16)].map(b => '0x' + b.toString(16).padStart(2, '0'));
      header += '\t' + row.join(', ') + ',\n';
    }
    header += '};\n';
    console.log(`OK  ${name}  ${file}  -> ${jpg.length} bytes`);
  }
  fs.writeFileSync(path.join(IMG_DIR, 'health_icons.h'), header);
  console.log(`\nheader: ${path.join(IMG_DIR, 'health_icons.h')}`);
})();
